[build-system]
requires = ["setuptools>=41.0", "wheel", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "pyg2p"
version = "3.2.8"
description = "Convert GRIB files to netCDF or PCRaster"
readme = "README.md"
license = {text = "EUPL 1.2"}
requires-python = "3.10"
authors = [
    {name = "Domenico Nappo", email = "domenico.nappo@gmail.com"},
    {name = "Carlo Russo", email = "carlo.russo@ext.ec.europa.eu"},
    {name = "Goncalo Gomes", email = "goncalo.ramos-gomes@ext.ec.europa.eu"}
]
keywords = ["NetCDF", "GRIB", "PCRaster", "Lisflood", "EFAS", "GLOFAS"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Other Audience",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: European Union Public Licence 1.2 (EUPL 1.2)",
    "Operating System :: Unix",
    "Operating System :: POSIX",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
    "gdal<=3.5.3",
    "netCDF4==1.7.4",
    "ujson>=5.4.0",
    "numpy==1.26.4",
    "numba>=0.64.0",
    "scipy==1.15.3",
    "numexpr>=2.7.1",
    "importlib-metadata<5.0.0",
    "dask[bag]",
    "dask[array]",
    "toolz",
    "eccodes",
    "lisflood-utilities",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
]

[project.scripts]
pyg2p = "pyg2p.main.api:main"

[tool.setuptools]
package-dir = {"" = "src/"}

[tool.setuptools.packages.find]
where = ["src/"]

[tool.setuptools.package-data]
pyg2p = ["*.json", "VERSION"]