name: Pyg2p Unit Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.7
    - name: Install python and gcc
      shell: bash -el {0}
      run: |
        conda install -c conda-forge python=3.7
        conda install -c conda-forge gcc=12.1.0
    - name: Install gdal
      shell: bash -el {0}
      run: |
        conda install -c conda-forge gdal eccodes
    - name: Install dependencies
      shell: bash -el {0}
      run: |
        pip install -r requirements.txt
    - name: Test with pytest
      shell: bash -el {0}
      run: |
        pip install pytest pytest-cov
        pytest